name: Build and push image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push devcontainer
        run: |
          npm install -g @devcontainers/cli 
          devcontainer build \
            --workspace-folder . \
            --cache-from ghcr.io/${{ github.repository }}:latest \
            --image-name ghcr.io/${{ github.repository }}:latest

          docker push ghcr.io/${{ github.repository }}:latest
