name: Build and push image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/radusuciu/snakemake-tutorial
          cacheFrom: ghcr.io/radusuciu/snakemake-tutorial
          push: always
